[versions]
activity = "1.13.0"
agp = "9.4.0"
appcompat = "1.8.0"
constraintlayout = "2.2.2"
material = "1.14.0"
work-runtime = "2.11.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "work-runtime" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
