[versions]
agp = "9.4.0"
coreKtx = "1.19.0"
appcompat = "1.8.0"
activity = "1.13.0"
material = "1.14.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

